version: '3.8'

services:
  backend: 
    build: ./backend
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 512M
  test:
    build: ./backend
    command: pytest /app/tests
    depends_on:
      - backend