name: Build, Test, and Deploy Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run application
        run: |
          docker compose up --build -d backend

      - name: Check memory usage
        run: free -m

      - name: Run tests with Pytest
        run: |
          docker compose run test

      - name: Shut down the application
        run: |
          docker compose down
