name: Build, Test, and Deploy Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add swap space
        run: |
          sudo fallocate -l 2G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build application with no cache
        run: |
          docker compose build --no-cache

      - name: Run application
        run: |
          docker compose up -d backend

      - name: Debug Container File Structure
        run: docker compose exec backend ls -R /app

      - name: Check memory usage
        run: free -m

      - name: Run tests with Pytest
        run: |
          docker compose exec backend pytest /app/app/tests

      - name: Shut down the application
        run: |
          docker compose down
